In [1]:
import numpy as np
import cv2
import time
from IPython.display import clear_output

%run math_calibration.ipynb

def get_available_cameras (upper_bound = 10, lower_bound = 0):
    available = []
    
    for i in range (lower_bound, upper_bound):
        cap = cv2.VideoCapture (i)
    
        if (cap.isOpened ()):
            available.append (i)
    
        cap.release ()
    
    return available

#get_available_cameras ()

#TODO: implement class, incapsulating input source
#possible inputs: video, camera, photo

CAMERA = 0
VIDEO  = 1
PHOTO  = 2

INPUT_SOURCE = CAMERA

cam_num = max (get_available_cameras ())

print (cam_num)

video_path = ""
video_file = ""

photo_path = "/Users/elijah/Dropbox/Programming/RoboCup/nao_cv/floor_desk/"
photo_file = "IMAGE_0_0_35.jpg"

cam = cv2.VideoCapture (cam_num)

if (INPUT_SOURCE != CAMERA):
    cam.release ()

if (INPUT_SOURCE == VIDEO):
    cam = cv2.VideoCapture (video_path + video_file)

elif (INPUT_SOURCE == PHOTO):
    img = cv2.imread (photo_path + photo_file)

cv2.namedWindow ("frame", cv2.WINDOW_NORMAL)

while (True):
    if (INPUT_SOURCE == CAMERA or INPUT_SOURCE == VIDEO):
        ret, frame = cam.read ()

    elif (INPUT_SOURCE == PHOTO):
        #print ("kek")
        frame = img.copy ()
    
    cv2.waitKey (1)    
    #resized = cv2.resize (frame, (960, 720))
    
    sz = 5
    shape = (sz, sz)
    
    calib_data = calibration_data (frame, shape, 51/8*sz)
    
    #if (calib_data == None):
    #    continue
    
    #print (calib_data)
    
    if (calib_data is not None):
        for key in calib_data.keys ():
            print (key + ": ", calib_data [key])

            if (key == "corners"):
                #print (calib_data [key])

                for i in range (3):
                    x = calib_data [key] [i, 0]
                    y = calib_data [key] [i, 1]

                    #print (x, y)

                    cv2.circle (frame, (int (x), int (y)), 7, (123, 234, 145), -1)

    cv2.imshow ("frame", frame)
    
    time.sleep (0.1)
    
    clear_output (wait=True)
    
    if (cv2.waitKey (1) & 0xFF == ord('q')):
        break

cam.release ()

cv2.destroyAllWindows()

opt_len:  943
incline:  60.6
turn   :  0.29
lens   :  [ 18.59162477 -25.25611403  68.55857668]
optical:  [  -2.33837309 -463.45859698  821.66586617]
corners:  [[ 75. 394.   0.]
 [117.  68.   0.]
 [492. 392.   0.]]


In [5]:
#arr = np.array ([[1]], np.uint8)
#print (cast (arr))

path = "/Users/elijah/Dropbox/Programming/RoboCup/nao_cv/floor_desk/"
file = "IMAGE_0_0_35.jpg"

img = cv2.imread (path + file)

_, corners = cv2.findChessboardCorners (img, (3, 3))

print (corners)

print (cast (corners))

[[[195.58002 175.85455]]

 [[236.79152 175.2833 ]]

 [[277.93045 174.5153 ]]

 [[318.5652  173.04854]]

 [[359.58334 173.62636]]

 [[400.54987 174.79799]]

 [[441.56024 174.55977]]

 [[189.33018 197.31569]]

 [[233.0029  196.33333]]

 [[276.3815  195.30241]]

 [[319.5183  194.4003 ]]

 [[362.5954  195.45412]]

 [[405.79147 196.00374]]

 [[449.17004 196.61412]]

 [[182.24664 221.93114]]

 [[228.50356 221.45505]]

 [[274.5053  220.48799]]

 [[320.43356 218.2249 ]]

 [[366.18097 220.28436]]

 [[411.8309  220.60376]]

 [[457.69266 220.86298]]

 [[174.30031 249.10228]]

 [[223.54288 248.47144]]

 [[272.68268 248.34909]]

 [[321.3567  245.4806 ]]

 [[370.02307 247.69383]]

 [[418.5618  248.49545]]

 [[467.81277 248.11949]]

 [[165.18752 280.6722 ]]

 [[218.27158 279.86685]]

 [[270.35815 278.8809 ]]

 [[322.47955 277.30646]]

 [[374.41776 278.45273]]

 [[426.41663 279.71588]]

 [[478.8296  279.62265]]

 [[154.29143 316.3992 ]]

 [[211.29738 315.12518]]

 [[267.5168  312.38098]]

 [[323.61203